source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'
gem 'aggregate_root'
gem 'zeitwerk'
gem 'pry'
gem 'dry-system'
gem 'dotenv'
gem 'rom'
gem 'rspec'
gem 'ruby_event_store'
gem 'rom-sql'
gem 'ruby_event_store-rom', require: 'ruby_event_store/rom/sql'
gem 'sqlite3'
gem 'rake'
gem 'curses'
gem 'aggregate_root'
gem 'pry'
